project:
  type: manuscript

manuscript:
  article: index.qmd
  notebooks:
    - notebook: notebooks/Data-management.qmd
      title: Data management
  meca-bundle: false
  
execute:
  freeze: true

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default




